# --- File Paths ---
paths:
  data: "data/spy_ohlcv_new.dbn"  # Main data file for training/backtesting

# --- Trading Parameters ---
trading:
  initial_cash: 100000.0
  commission_spread_points: 0.8
  stake_size: 10
  train_test_split_ratio: 0.8

# --- Active Strategy ---
active_strategy: "ml_moving_average_crossover"

# --- Strategy Configurations ---
strategies:
  # Moving Average Crossover with ML
  ml_moving_average_crossover:
    # Technical Parameters
    short_window: 40
    long_window: 100
    
    # Feature Engineering
    features:
      volatility_window: 20
      rsi_window: 14
      feature_list: ['returns', 'volatility', 'rsi']
    
    # Model Configuration  
    model:
      path: "data/ml_moving_average_model.joblib"
      probability_threshold: 0.70

  # Opening Range Breakout
  ml_open_range_breakout:
    # Time Parameters
    range:
      start: "09:30:00"
      end: "10:00:00"
    
    # Risk Management
    risk:
      take_profit_multiplier: 1.0
      stop_loss_multiplier: 0.5
    
    # Feature Engineering
    features:
      volatility_window: 20
      rsi_window: 14
      feature_list: ['returns', 'volatility', 'rsi', 'is_nr4', 'is_nr7']
    
    # Model Configuration
    model:
      path: "data/ml_orb_model.joblib"
      probability_threshold: 0.70