# --- General Settings for the Bot ---
general:
  initial_cash: 100000.0
  commission_spread_points: 0.8
  data_file_path: "data/spy_ohlcv_new.dbn" # Use the .dbn file
  train_test_split_ratio: 0.8
  stake_size: 10 # Added stake size here for the backtester

# --- Active Strategy Selection ---
# This tells the bot which strategy to load and run.
active_strategy: "ml_moving_average_crossover"

# --- Strategy-Specific Parameter Sets ---
# Each key here must match a strategy name in strategies/__init__.py
strategies:
  ml_moving_average_crossover:
    short_window: 40
    long_window: 100
    feature_vol_window: 20
    feature_rsi_window: 14
    model_file_path: "data/profit_model.joblib"
    probability_threshold: 0.60
    # The list of features for the model to use
    feature_list: ['returns', 'volatility', 'rsi']

  # Example for a future strategy, you can leave it commented out
  # rsi_mean_reversion:
  #   rsi_period: 14
  #   oversold: 30
  #   overbought: 70
  #   model_file_path: "data/rsi_reversion_model.joblib"
  #   probability_threshold: 0.55
  #   feature_list: ['rsi']